
windowrule {
  name = wifi-ctl
  match:class = org.twosheds.iwgtk
  float = on
  size = 650 600 
  move = (monitor_w-660) 50
  animation = slide right
  opacity = 0.95
}

windowrule {
  name = wifi-passwd
  match:class = iwgtk
  float = on
  size = 0 0 
  move = (cursor_x-200) cursor_y
  opacity = 0.95
}

windowrule {
  name = audio-ctl
  match:class = org.pulseaudio.pavucontrol
  float = on
  size = 650 600 
  move = (monitor_w-660) 50
  animation = slide right
  opacity = 0.95
}

windowrule {
  name = bluetooth-ctl
  match:class = blueman-manager
  float = on
  size = 600 600 
  move = (monitor_w-610) 50
  animation = slide right
  opacity = 0.95
}
