font_family         JetBrainsMono Nerd Font
italic_font         auto
bold_font           auto
bold_italic_font    auto

font_size   12.0

disable_ligatures always

foreground  #dddddd

background  #242424

background_opacity 0.8

cursor_shape    block
cursor_shape_unfocused hollow

cursor_blink_interval   0.5

term    xterm-kitty
